# Generated by Django 3.1.1 on 2021-04-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentProfile',
        ),
    ]
