# Generated by Django 3.1.1 on 2021-04-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='country',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='teacherImages'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='state',
            field=models.CharField(default='', max_length=25),
        ),
    ]
