# Generated by Django 3.1.1 on 2021-04-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210404_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='lastname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='firstname',
        ),
    ]
