# Generated by Django 3.1.1 on 2021-04-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20210404_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='tagline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
