# Generated by Django 3.1.1 on 2021-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_teacherprofile_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='tagline',
            field=models.CharField(default='Keep Learning', max_length=100),
        ),
    ]
