# Generated by Django 3.1.1 on 2021-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20210404_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
