# Generated by Django 3.1.1 on 2021-04-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_follower_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='profileImage',
            field=models.ImageField(blank=True, default='teacherImages/def_user.png', upload_to='teacherImages'),
        ),
    ]
