# Generated by Django 3.1.1 on 2021-04-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210405_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='course_thumbnails'),
        ),
    ]
