# Generated by Django 3.1.1 on 2021-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210405_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='def_cour_thum', upload_to='course_thumbnails'),
        ),
    ]
