# Generated by Django 3.1.1 on 2021-04-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210405_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='course_thumbnails/def_cour_thumb.jpeg', upload_to='course_thumbnails'),
        ),
    ]
