# Generated by Django 3.1 on 2021-04-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210405_1919'),
        ('courses', '0011_video_video_title'),
    ]

    operations = [
    ]
