# Generated by Django 3.1.1 on 2021-04-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_merge_20210405_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_title',
        ),
    ]
