# Generated by Django 3.1.1 on 2021-04-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210405_1908'),
        ('courses', '0014_remove_video_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes_post', to='student.studentProfile'),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='likes_post', to='student.studentProfile'),
        ),
    ]
