# Generated by Django 3.1.1 on 2021-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210407_1622'),
        ('courses', '0019_auto_20210410_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='tot_views', to='student.studentProfile'),
        ),
    ]
