# Generated by Django 3.1.1 on 2021-04-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210410_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
