# Generated by Django 3.1 on 2021-04-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20210410_0035'),
        ('courses', '0019_subscription'),
    ]

    operations = [
    ]
