# Generated by Django 3.1.1 on 2021-04-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_merge_20210410_1046'),
        ('courses', '0023_merge_20210410_1043'),
    ]

    operations = [
    ]
