# Generated by Django 3.1 on 2021-04-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_merge_20210410_1043'),
        ('courses', '0023_merge_20210410_1046'),
    ]

    operations = [
    ]
