# Generated by Django 3.1 on 2021-04-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_merge_20210410_1552'),
        ('courses', '0024_merge_20210410_1238'),
    ]

    operations = [
    ]
