# Generated by Django 3.1.1 on 2021-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='teacherImages'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tagline',
            field=models.CharField(default='Keep Learning', max_length=100),
        ),
    ]
