# Generated by Django 3.1.1 on 2021-04-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210405_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='studentImages'),
        ),
    ]
