# Generated by Django 3.1.1 on 2021-04-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20210404_1546'),
        ('student', '0003_auto_20210405_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
                ('teachers', models.ManyToManyField(related_name='followed', to='teacher.teacherProfile')),
            ],
        ),
    ]
