# Generated by Django 3.1.1 on 2021-04-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210407_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
